### ISSUE TITLE
Core Versioning Conundrum

### ISSUE THREAD

**Issue by jaswsinc** [websharks/core#1]
Versioning the websharks/core and websharks/wp-core is a tricky thing to deal with. Tricky why? If a piece of software bundles the websharks/core, it is going to depend on this being at a specific version of the websharks/core.

## Conundrum?

- Imagine software package A (depends on websharks/core).
- Imagine software package B (also depends on websharks/core).
- Imagine software package C (depends on package A and package B, and also on the webshares/core).

So, we can see in this example that it is possible for A, B, and C to all be working together in a single process. What happens when package A was coded for version 1.1 of websharks/core, package B was coded for version 1.2 of websharks/core, and package C was coded for version 1.3 of websharks/core?

When I say, "coded for", I mean that a specific version of the websharks/core may behave a bit differently. One version might come with functionality that a previous version did not have, etc, etc.

Of course we will work to update packages A, B, and C so they are all compatible with the latest/greatest core; but this will not always be the case at all times; i.e., software we distribute needs to be capable of working as it was designed, even if package B is updated to use the latest version of the websharks/core, while packages A and C still need to be updated.

## WordPress Example

Imagine package A, B, and C are all WordPress plugins; i.e., all being loaded into a single process. It's the same situation as I outlined above, but it becomes a little clearer when thinking about it this way.

## SPL Autoloading To the Rescue?

No. A PHP class (i.e., class, interface, or trait) is an identifier. It is either loaded or not. If the websharks/core comes with class X, and it is not loaded yet, PHP will autoload that class file using one of the currently registered autoload handlers.

The problem, again, is that class X could be loaded from one of three possible locations. Either from software package A, B, or C. Depending on which of these are used to fill the autoload request, a different version of the class file might be loaded; and thus shared by all packages.

If package B is using the latest version of the websharks/core, and it fills the autoload request, packages A and C might cause an error, because they are expecting to see a different version of the websharks/core; i.e., the version they were originally built for and tested against.

## Core Dependencies

Understanding _how_ the websharks/core and websharks/wp-core are going to be used is key. These are not simply dependencies; these core libraries are going to be used as a base to start from, and then a software package is built from that base by extending classes and/or utilizing utilities provided by the core. Therefore, it is important that each software package be connected to a specific version of the websharks/core. When it is possible for the core to updated in that package, we can do so; but not before! Certainly not at runtime by accident; i.e., when another package happens to load a different version of the websharks/core.

## Possible Solutions

- Use PHP v5.4 Traits and name each trait with a version suffix. This makes the core more difficult to maintain, and it requires a lot of search/replace whenever the core itself is updated. The same whenever a package is updated that relies on a specific version of the core.
- Use class aliases together with a custom autoloader that can distinguish one version from another. This is not ideal, because class aliases are more difficult to work with in IDEs that are unaware of such things. Also, this makes the core harder to work with too, because every change will require a version bump in the name of each Trait.
- Use the core not as a dependency at all, but as a library that becomes part of each software package, and each software package would include a build script that alters the namespace of all core packages; i.e., core libraries are used as a base, but renamed; becoming a part of each software package it is used in. The big downsides here are that it's not nearly as clean, harder to maintain, and we lose the optimization that having a central "core" library would offer.
- ... I'll add other ideas here as they come to me.

**Comment by jaswsinc** [comment]
Solving this problem would make a fantastic article for the WP community. If we find a way to work around this problem, it would not only help us for the core, but it would make it much easier for WP plugin developers to bundle other software packages with their plugin; i.e., enhance functionality and reduce their own overhead.

As it stands right now, each WP plugin has to be very careful about introducing a class dependency that might conflict with another software package that happens to be running on a given site.

A simple example of this is something like the MailChimp or Stripe SDK. If s2Member bundles these dependencies (it does), what happens when a site owner adds a plugin that also introduces the same dependency?

s2Member currently checks `class_exists()` to avoid loading the class twice, but that's operating under the assumption that if it is already loaded, we can rely on the already-loaded class to do the job. That's not a safe assumption, because the already-loaded class file might actually be an entirely different version of the Stripe SDK or MailChimp SDK.

**Comment by jaswsinc** [comment]
It would be cool if PHP itself introduced "namespace versioning". A syntax that would allow the same namespace to be duplicated at runtime in order to fill version-specific dependencies.

Technically, this is already possible to do; e.g., `my\namespace\v2`. This is not even close to practical though, because the version reference should occur in each call, not in the library itself. For instance, we can't expect Stripe to namespace every version of their SDK with a version suffix.

**Comment by raamdev** [comment]
Hmm, yup, I see the conundrum. 

Regardless of what route we take to get around this, I think this only exemplifies the needs for a full testing suite for our plugins. If we made changes to a core package, we need to be able to easily run a set of automated tests for a given plugin that makes sure compatibility doesn't break.

It also makes sense that we'd want to update a websharks/core or websharks/wp-core package as infrequently as possible, as any one update would require testing how that change might affect all software packages (e.g., WordPress plugins) that are depending on websharks/core or websharks/wp-core. 

> Imagine software package C (depends on package A and package B, and also on the webshares/core).

In that scenario, if package C depended on different version of websharks/core or websharks/wp-core than package A and package B, I would expect package A and package B to include a separate version of websharks/core or websharks/wp-core that those packages use (certainly not ideal, but it _would_ be motivation to update those packages so that they all use the latest version of core or wp-core).

> Use the core not as a dependency at all, but as a library that becomes part of each software package, and each software package would include a build script that alters the namespace of all core packages;

This wouldn't be that hard to maintain if we have scripts automating the process, i.e., if we have a build process configured for each plugin, the build process could handle all the necessary modifications in a few seconds, creating a distributable version of the software that has been configured to use whatever version of core or wp-core we chose.

**Comment by jaswsinc** [comment]
@raamdev writes...
> This wouldn't be that hard to maintain if we have scripts automating the process, i.e., if we have a build process configured for each plugin, the build process could handle all the necessary modifications in a few seconds, creating a distributable version of the software that has been configured to use whatever version of core or wp-core we chose.

Thanks for your input here.
Agree. This is the direction I am leaning in right now also.

**Comment by jaswsinc** [comment]
I'm going to close this now. I went with Phing build scripts that deal with packaging the core and altering the namespace of core packages to make them a part of the software that is using them. The core could be run stand-alone also this way. In short, what we already discussed prior.

---

In addition, the core is going to consist of many Traits, and there will be a PHP v5.4+ requirement in any application that uses the WebSharks Core; i.e., any future software packages that we build will have a PHP v5.4 requirement. Traits make this much easier to manage, since Traits can be reused in any class, and also become dependencies of other Traits. Beautiful! This will increase the mileage that we can get out of core utilities.

**Comment by jaswsinc** [comment]
@raamdev I should clarify the PHP v5.4 requirement.

The current release of the HTML Compressor, JS Minifier, and of ZenCache require PHP v5.3+; i.e., these do not make use of the Core yet, and I do not have plans to do change that at this time. For instance, the ZenCache restructuring is about restructuring what already exists in this plugin, not to alter it in ways that would add a dependency that requires the new WSC (WebSharks Core) or PHP v5.4+.

Having said that, please let me know whenever you reach a point where you are ready to bump the minimum requirement in ZenCache up to 5.4+. I'm ready for this at any time, but until I hear that you are also, I'm operating with PHP v5.3 in mind.

**Comment by raamdev** [comment]
> The current release of the HTML Compressor, JS Minifier, and of ZenCache require PHP v5.3+; i.e., these do not make use of the Core yet, and I do not have plans to do change that at this time

@jaswsinc Thanks for mentioning that--I was wondering. :-) 

> Having said that, please let me know whenever you reach a point where you are ready to bump the minimum requirement in ZenCache up to 5.4+. I'm ready for this at any time, but until I hear that you are also, I'm operating with PHP v5.3 in mind.

Copy that. I'd like to revisit this a bit later, maybe towards Q3/Q4. If WordPress bumps their minimum required PHP version, which I have a feeling they're going to do this year (no basis for this, just a feeling), that would be a good time to do the same. 

> I'm going to close this now. I went with Phing build scripts that deal with packaging the core and altering the namespace of core packages to make them a part of the software that is using them

Great! I love that we're using Phing.

**Comment by jaswsinc** [comment]
> which I have a feeling they're going to do this year (no basis for this, just a feeling), that would be a good time to do the same.

Copy that.
